version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/transport
    networks:
      - backend
    volumes:
      - logs:/app/logs

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080" 
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    command: ["node", "server.js"]

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transport
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  logs:

networks:
  backend:
    internal: true
  frontend:
